language: go
sudo: false
go:
  - 1.9

before_script:
  - go vet .

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/vendor/bin:$PATH"

script:
  - go build -race
  - go test . -race
